import puppeteer from 'file:///C:/Users/artom/Projects/ApexRunAI/30-marketing/content-library/_render/node_modules/puppeteer-core/lib/esm/puppeteer/puppeteer-core.js';
const CHROME='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const URL='file:///C:/Users/artom/Downloads/AIA%20Clients/Scruples/scruples-demo/index.html';
const OUT='C:/Users/artom/Downloads/AIA Clients/Scruples/scruples-demo/';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const nav=id=>`(()=>{const n=[...document.querySelectorAll('.nav__item')].find(x=>x.dataset.id==='${id}');n&&n.click();})()`;
const b=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox','--force-color-profile=srgb']});
const p=await b.newPage(); await p.setViewport({width:1440,height:900,deviceScaleFactor:1}); p.setDefaultTimeout(15000);
let errs=[]; p.on('pageerror',e=>errs.push('PAGEERR '+e.message));
await p.goto(URL,{waitUntil:'domcontentloaded'}); await sleep(2000);
await p.click('#demoBtn'); await sleep(1500);
await p.evaluate(nav('social')); await sleep(1300); await p.screenshot({path:OUT+'shot-5-social.png'});
await p.evaluate(nav('comments')); await sleep(1300); await p.screenshot({path:OUT+'shot-6-comments.png'});
await p.evaluate(nav('knowledge')); await sleep(1300); await p.screenshot({path:OUT+'shot-7-knowledge.png'});
await p.evaluate(nav('integrations')); await sleep(1300); await p.screenshot({path:OUT+'shot-8-integrations.png'});
await p.evaluate(()=>document.querySelector('#themeBtn').click()); await p.evaluate(nav('overview')); await sleep(1500);
await p.screenshot({path:OUT+'shot-9-dark.png'});
console.log('done · ERRORS:', errs.length?JSON.stringify(errs):'none');
await b.close();
